#!/usr/bin/env python3
"""
interactives/index.html 자동 생성기.

각 interactives/*.html 상단 주석 frontmatter(title/date/status/category)를
단일 진실원천으로 삼아 카탈로그 페이지를 생성한다. 수기 카드 추가를 없애
도구 누락(invisible) 재발을 막는다.

실행: python3 scripts/build-interactives-index.py   (repo 루트 기준)
출력: interactives/index.html  (덮어쓰기)

category 미지정/미정의 파일은 '기타 · 미분류' 버킷으로 떨어져 절대 누락되지 않는다.
"""

import re
import sys
import html
from pathlib import Path

# 스크립트 위치 기준으로 repo 경로 해석 (cwd 무관)
ROOT = Path(__file__).resolve().parent.parent
INTERACTIVES = ROOT / "interactives"
OUT = INTERACTIVES / "index.html"

# 카테고리 표시 순서 + 한글 라벨. 키는 frontmatter의 category: 값과 일치.
CATEGORIES = [
    ("isq",       "ISQ · RFA · 부하 결정"),
    ("surgery",   "수술 · 술식 의사결정"),
    ("materials", "재료 · 접착 · 약물"),
    ("caries",    "우식 · 예방 · 미생물"),
    ("patient",   "환자 커뮤니케이션"),
    ("meta",      "메타 · 위키 성장"),
]
FALLBACK_KEY = "_misc"
FALLBACK_LABEL = "기타 · 미분류"

# status -> badge CSS class (index.html <style>에 정의됨). 미지정은 draft로.
KNOWN_STATUS = {"done", "review", "in-progress", "draft"}


def parse_frontmatter(text: str) -> dict:
    """상단 <!-- --- ... --- --> 주석 블록에서 key: value 추출."""
    m = re.search(r"<!--\s*\n---\s*\n(.*?)\n---\s*\n-->", text, flags=re.S)
    block = m.group(1) if m else text[:800]
    fm = {}
    for line in block.split("\n"):
        km = re.match(r"^([a-zA-Z_]+):\s*(.*)$", line)
        if km:
            key, val = km.group(1), km.group(2).strip()
            val = val.strip('"').strip("'")
            if key not in fm:  # 첫 등장만 (중첩 source_wiki 등 무시)
                fm[key] = val
    return fm


def collect():
    tools = []
    for p in sorted(INTERACTIVES.glob("*.html")):
        if p.name == "index.html":
            continue
        fm = parse_frontmatter(p.read_text(encoding="utf-8"))
        cat = fm.get("category", "").strip() or FALLBACK_KEY
        valid_keys = {k for k, _ in CATEGORIES}
        if cat not in valid_keys:
            cat = FALLBACK_KEY
        status = fm.get("status", "draft").strip()
        if status not in KNOWN_STATUS:
            status = "draft"
        tools.append({
            "file": p.name,
            "title": fm.get("title", p.stem),
            "date": fm.get("date", ""),
            "status": status,
            "category": cat,
        })
    return tools


def render_card(t: dict) -> str:
    title = html.escape(t["title"])
    return (
        f'      <a class="card" href="{t["file"]}">\n'
        f'        <p class="t">{title}</p>\n'
        f'        <div class="meta"><span class="date">{t["date"]}</span>'
        f'<span class="badge {t["status"]}">{t["status"]}</span></div>\n'
        f'      </a>'
    )


def render_section(label: str, items: list) -> str:
    cards = "\n".join(render_card(t) for t in items)
    return (
        f'  <section>\n'
        f'    <h2>{html.escape(label)}</h2>\n'
        f'    <div class="grid">\n{cards}\n    </div>\n'
        f'  </section>'
    )


HEAD = """<!--
---
title: "LLM Wiki — Interactive Tools 색인"
type: interactive
date: AUTO
status: done
note: "AUTO-GENERATED by scripts/build-interactives-index.py — 손으로 편집하지 말 것. 새 도구는 interactives/에 frontmatter(category 포함) 달고 떨구면 빌드가 카드를 만든다."
---
-->
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>LLM Wiki — Interactive Tools 색인</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>
  :root {
    --bg: #faf8f8;
    --card: #ffffff;
    --line: #e5e5e5;
    --gray: #b8b8b8;
    --dark: #2b2b2b;
    --muted: #6b6b6b;
    --secondary: #284b63;
    --tertiary: #84a59d;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: "Noto Sans KR", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    background: var(--bg);
    color: var(--dark);
    line-height: 1.6;
    -webkit-font-smoothing: antialiased;
  }
  .wrap { max-width: 1000px; margin: 0 auto; padding: 48px 24px 80px; }
  header { border-bottom: 2px solid var(--secondary); padding-bottom: 20px; margin-bottom: 8px; }
  h1 { font-size: 1.9rem; margin: 0 0 6px; color: var(--secondary); letter-spacing: -0.01em; }
  .sub { color: var(--muted); font-size: 0.95rem; margin: 0; }
  .sub code { font-family: "JetBrains Mono", monospace; background: #eef1f3; padding: 1px 6px; border-radius: 4px; font-size: 0.85em; }
  .count { display: inline-block; background: var(--tertiary); color: #fff; font-weight: 700; border-radius: 999px; padding: 2px 12px; font-size: 0.85rem; margin-left: 8px; vertical-align: middle; }

  section { margin-top: 40px; }
  h2 { font-size: 1.15rem; color: var(--secondary); margin: 0 0 16px; padding-left: 12px; border-left: 4px solid var(--tertiary); }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; }

  a.card {
    display: block; background: var(--card); border: 1px solid var(--line); border-radius: 12px;
    padding: 18px 20px; text-decoration: none; color: inherit;
    transition: transform .12s ease, box-shadow .12s ease, border-color .12s ease;
  }
  a.card:hover { transform: translateY(-3px); box-shadow: 0 8px 24px rgba(40,75,99,.12); border-color: var(--tertiary); }
  .card .t { font-weight: 700; font-size: 1rem; color: var(--secondary); margin: 0 0 10px; }
  .meta { display: flex; align-items: center; gap: 10px; font-size: 0.8rem; color: var(--muted); }
  .date { font-family: "JetBrains Mono", monospace; }
  .badge { font-size: 0.7rem; font-weight: 600; padding: 2px 9px; border-radius: 999px; text-transform: uppercase; letter-spacing: 0.03em; }
  .badge.done       { background: #e6f4ea; color: #1e7e34; }
  .badge.review     { background: #fff4e0; color: #b8860b; }
  .badge.in-progress{ background: #e7f0fa; color: #2c6cb0; }
  .badge.draft      { background: #f0f0f0; color: #8a8a8a; }

  footer { margin-top: 56px; padding-top: 20px; border-top: 1px solid var(--line); color: var(--gray); font-size: 0.82rem; }
  footer a { color: var(--secondary); }
</style>
</head>
<body>
<div class="wrap">
"""

FOOTER = """
  <footer>
    LLM Wiki — Dentistry · <strong>자동 생성</strong> 색인 (scripts/build-interactives-index.py).
    새 도구는 <code>interactives/</code>에 frontmatter(<code>category:</code> 포함)와 함께 떨구면 빌드가 카드를 만듭니다.
    · <a href="../">← 위키 홈</a>
  </footer>
</div>
</body>
</html>
"""


def main():
    tools = collect()
    total = len(tools)

    # 카테고리별 그룹핑, 그룹 내 date 내림차순 (동률은 파일명 내림차순)
    by_cat = {}
    for t in tools:
        by_cat.setdefault(t["category"], []).append(t)
    for items in by_cat.values():
        items.sort(key=lambda x: (x["date"], x["file"]), reverse=True)

    order = CATEGORIES + [(FALLBACK_KEY, FALLBACK_LABEL)]
    sections = []
    for key, label in order:
        if by_cat.get(key):
            sections.append(render_section(label, by_cat[key]))

    header = (
        f'  <header>\n'
        f'    <h1>🦷 Interactive Tools <span class="count">{total}</span></h1>\n'
        f'    <p class="sub">LLM Wiki 치과학 — chairside 계산기·의사결정 트리·시뮬레이터 모음. '
        f'모든 도구는 wiki 근거에 연결된 자체완결 HTML입니다. 경로: <code>/interactives/</code></p>\n'
        f'  </header>'
    )

    out = HEAD + header + "\n\n" + "\n\n".join(sections) + "\n" + FOOTER
    OUT.write_text(out, encoding="utf-8")
    print(f"[build-interactives-index] {total} tools → {OUT.relative_to(ROOT)}")

    # 미분류 경고 (빌드 실패는 아님 — visibility 신호)
    misc = by_cat.get(FALLBACK_KEY, [])
    if misc:
        print(f"  WARNING: {len(misc)} tool(s) without valid category → '기타·미분류':", file=sys.stderr)
        for t in misc:
            print(f"    - {t['file']}", file=sys.stderr)


if __name__ == "__main__":
    main()
