#!/usr/bin/env python3
"""
lectures/index.html 자동 생성기.

각 lectures/*.html (slides/*.md를 Marp로 export한 정적 덱) 상단 주석
frontmatter(title/date/status/audience/duration/agenda)를 단일 진실원천으로
삼아 카탈로그 페이지를 생성한다. interactives/index.html과 같은 패턴이지만
별도 폴더 — 슬라이드 덱은 계산기/결정트리와 성격이 달라 분리.

실행: python3 scripts/build-lectures-index.py   (repo 루트 기준)
출력: lectures/index.html  (덮어쓰기)
신규 덱 추가: bash scripts/export-slides.sh 로 slides/*.md를 재수출한 뒤 이 스크립트 실행.
"""

import re
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LECTURES = ROOT / "lectures"
OUT = LECTURES / "index.html"

KNOWN_STATUS = {"done", "review", "in-progress", "draft"}
FALLBACK_AUDIENCE = "기타"


def parse_frontmatter(text: str) -> dict:
    m = re.search(r"<!--\s*\n---\s*\n(.*?)\n---\s*\n-->", text, flags=re.S)
    block = m.group(1) if m else text[:800]
    fm = {}
    for line in block.split("\n"):
        km = re.match(r"^([a-zA-Z_]+):\s*(.*)$", line)
        if km:
            key, val = km.group(1), km.group(2).strip()
            val = val.strip('"').strip("'")
            if key not in fm:
                fm[key] = val
    return fm


def collect():
    decks = []
    for p in sorted(LECTURES.glob("*.html")):
        if p.name == "index.html":
            continue
        fm = parse_frontmatter(p.read_text(encoding="utf-8"))
        status = fm.get("status", "draft").strip()
        if status not in KNOWN_STATUS:
            status = "draft"
        decks.append({
            "file": p.name,
            "title": fm.get("title", p.stem),
            "date": fm.get("date", ""),
            "status": status,
            "audience": fm.get("audience", "").strip() or FALLBACK_AUDIENCE,
            "duration": fm.get("duration", "").strip(),
        })
    return decks


def render_card(d: dict) -> str:
    title = html.escape(d["title"])
    dur = f'<span class="dur">{html.escape(d["duration"])}</span>' if d["duration"] else ""
    return (
        f'      <a class="card" href="{d["file"]}">\n'
        f'        <p class="t">{title}</p>\n'
        f'        <div class="meta"><span class="date">{d["date"]}</span>'
        f'<span class="badge {d["status"]}">{d["status"]}</span>{dur}</div>\n'
        f'      </a>'
    )


def render_section(label: str, items: list) -> str:
    cards = "\n".join(render_card(d) for d in items)
    return (
        f'  <section>\n'
        f'    <h2>{html.escape(label)}</h2>\n'
        f'    <div class="grid">\n{cards}\n    </div>\n'
        f'  </section>'
    )


HEAD = """<!--
---
title: "LLM Wiki — 강의·교육 슬라이드 색인"
type: lecture
date: AUTO
status: done
note: "AUTO-GENERATED by scripts/build-lectures-index.py — 손으로 편집하지 말 것. 새 덱은 slides/*.md 작성 후 bash scripts/export-slides.sh 로 lectures/에 export하면 빌드가 카드를 만든다."
---
-->
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>LLM Wiki — 강의·교육 슬라이드 색인</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>
  :root {
    --bg: #faf8f8;
    --card: #ffffff;
    --line: #e5e5e5;
    --gray: #b8b8b8;
    --dark: #2b2b2b;
    --muted: #6b6b6b;
    --secondary: #284b63;
    --tertiary: #84a59d;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: "Noto Sans KR", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    background: var(--bg);
    color: var(--dark);
    line-height: 1.6;
    -webkit-font-smoothing: antialiased;
  }
  .wrap { max-width: 1000px; margin: 0 auto; padding: 48px 24px 80px; }
  header { border-bottom: 2px solid var(--secondary); padding-bottom: 20px; margin-bottom: 8px; }
  h1 { font-size: 1.9rem; margin: 0 0 6px; color: var(--secondary); letter-spacing: -0.01em; }
  .sub { color: var(--muted); font-size: 0.95rem; margin: 0; }
  .sub code { font-family: "JetBrains Mono", monospace; background: #eef1f3; padding: 1px 6px; border-radius: 4px; font-size: 0.85em; }
  .count { display: inline-block; background: var(--tertiary); color: #fff; font-weight: 700; border-radius: 999px; padding: 2px 12px; font-size: 0.85rem; margin-left: 8px; vertical-align: middle; }

  section { margin-top: 40px; }
  h2 { font-size: 1.15rem; color: var(--secondary); margin: 0 0 16px; padding-left: 12px; border-left: 4px solid var(--tertiary); }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; }

  a.card {
    display: block; background: var(--card); border: 1px solid var(--line); border-radius: 12px;
    padding: 18px 20px; text-decoration: none; color: inherit;
    transition: transform .12s ease, box-shadow .12s ease, border-color .12s ease;
  }
  a.card:hover { transform: translateY(-3px); box-shadow: 0 8px 24px rgba(40,75,99,.12); border-color: var(--tertiary); }
  .card .t { font-weight: 700; font-size: 1rem; color: var(--secondary); margin: 0 0 10px; }
  .meta { display: flex; align-items: center; gap: 10px; font-size: 0.8rem; color: var(--muted); flex-wrap: wrap; }
  .date { font-family: "JetBrains Mono", monospace; }
  .dur { font-family: "JetBrains Mono", monospace; color: var(--tertiary); }
  .badge { font-size: 0.7rem; font-weight: 600; padding: 2px 9px; border-radius: 999px; text-transform: uppercase; letter-spacing: 0.03em; }
  .badge.done       { background: #e6f4ea; color: #1e7e34; }
  .badge.review     { background: #fff4e0; color: #b8860b; }
  .badge.in-progress{ background: #e7f0fa; color: #2c6cb0; }
  .badge.draft      { background: #f0f0f0; color: #8a8a8a; }

  footer { margin-top: 56px; padding-top: 20px; border-top: 1px solid var(--line); color: var(--gray); font-size: 0.82rem; }
  footer a { color: var(--secondary); }
</style>
</head>
<body>
<div class="wrap">
"""

FOOTER = """
  <footer>
    LLM Wiki — Dentistry · <strong>자동 생성</strong> 색인 (scripts/build-lectures-index.py).
    새 덱은 <code>slides/*.md</code> 작성 후 <code>bash scripts/export-slides.sh</code>로 export하면 빌드가 카드를 만듭니다.
    · <a href="../">← 위키 홈</a>
  </footer>
</div>
</body>
</html>
"""


def main():
    decks = collect()
    total = len(decks)

    by_aud = {}
    for d in decks:
        by_aud.setdefault(d["audience"], []).append(d)
    for items in by_aud.values():
        items.sort(key=lambda x: (x["date"], x["file"]), reverse=True)

    # 오디언스 라벨은 고정 카테고리가 아니라 frontmatter 자유 텍스트라
    # 최신 덱 날짜 기준으로 섹션 순서를 정한다 (기타는 항상 마지막).
    order = sorted(
        (k for k in by_aud if k != FALLBACK_AUDIENCE),
        key=lambda k: max(d["date"] for d in by_aud[k]),
        reverse=True,
    )
    if FALLBACK_AUDIENCE in by_aud:
        order.append(FALLBACK_AUDIENCE)

    sections = [render_section(k, by_aud[k]) for k in order]

    header = (
        f'  <header>\n'
        f'    <h1>강의·교육 슬라이드<span class="count">{total}</span></h1>\n'
        f'    <p class="sub">위키 근거를 기반으로 만든 세미나·직원 교육용 Marp 덱. '
        f'<code>slides/*.md</code>가 소스, 여기 있는 것은 export된 정적 발표 화면입니다.</p>\n'
        f'  </header>\n'
    )

    out = HEAD + header + "\n".join(sections) + FOOTER
    OUT.write_text(out, encoding="utf-8")
    print(f"[build-lectures-index] {total} decks → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
